FROM node:20-alpine AS build
WORKDIR /client
COPY package*.json ./
RUN npm ci
COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /client/build /usr/share/nginx/html
EXPOSE 80